<?php

/**
 * @file
 * Provides integration with Salesforce for the NLC Connect service.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Form;
use Drupal\node\Entity\NodeType;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\salesforce\SFID;

use Drupal\nlc_salesforce\SFAPI\SFWrapper;

/**
 * Define custom templates.
 */
function nlc_salesforce_theme($existing, $type, $theme, $path) {
  return [
    'nlc_field' => [
      'variables' => [
        'label' => NULL,
        'content' => NULL,
      ]
    ]
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function nlc_salesforce_entity_extra_field_info() {
  $extra = array();

  foreach(SFWrapper::CONTACT_FIELDS as $id => $details) {
    $extra['user']['user']['display'][$id] = [
      'label' => t($details['label']),
      'description' => t($details['description']),
      'visible' => TRUE,
      'weight' => 100,
    ];
  }
 
  return $extra;
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function nlc_salesforce_user_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  $client = SFWrapper::getInstance();
  $values = $client->getDetailsFromEntity($entity);

  foreach(SFWrapper::CONTACT_FIELDS as $id => $details) {

    if ($component = $display->getComponent($id)) {
      $build[$id] = [
        '#theme' => 'nlc_field',
        '#content' => $values[$details['sf_field']] ?? NULL,
        '#label' => $details['label'],
      ];
    }
  }
}
