<?php

namespace Drupal\neo4j_db_entity\Model\User;

use Drupal\Core\Entity\EntityInterface;
use Drupal\neo4j_db_entity\Model\AbstractGraphEntityModelBase;
use GraphAware\Neo4j\OGM\Annotations as OGM;

/**
 * Class GraphEntityUserUserModel
 *
 * @package Drupal\neo4j_db_entity\Model\User
 *
 * @OGM\Node(label="User")
 */
class GraphEntityUserUserModel extends AbstractGraphEntityModelBase implements GraphEntityUserModelInterface {

  protected $entityType = 'user';

  protected $bundle = 'user';

  protected $type = 'User';

  /**
   * @var int
   *
   * @OGM\GraphId()
   */
  protected $id;

  /**
   * @var int
   *
   * @OGM\Property(type="int")
   */
  protected $entityId;

  /**
   * @var string
   *
   * @OGM\Property(type="string")
   */
  protected $name;

  /**
   * @var \Drupal\user\UserInterface
   */
  protected $entity;

  /**
   * @var
   */
  protected $graphEntity;

  protected $visit;


  /**
   * {@inheritDoc}
   */
  public function buildModel() {
    parent::buildModel(); // TODO: Change the autogenerated stub
    $this->setEntityId($this->entity()->id());
    $this->setName($this->entity()->getAccountName());
    return $this;
  }

  public function getGraphEntity() {
    return $this->connection->findOneBy(__CLASS__, $this->findOneByCriteria());
  }

  /**
   * {@inheritDoc}
   */
  public function entity() {
    /** @var \Drupal\user\UserInterface $entity */
    $entity = parent::entity();
    return $entity;
  }

  /**
   * {@inheritDoc}
   */
  public function baseFindOneByCriteria() {
    return ['entityId' => intval($this->entity()->id())];
  }

  /**
   * @return int
   */
  public function getId(): int {
    return $this->id;
  }

  /**
   * @param int $entityId
   */
  public function setEntityId(int $entityId): void {
    $this->entityId = $entityId;
  }

  /**
   * @return int
   */
  public function getEntityId(): int {
    return $this->entityId;
  }

  /**
   * @param string $name
   */
  public function setName(string $name): void {
    $this->name = $name;
  }

  /**
   * @return string
   */
  public function getName(): string {
    return $this->name;
  }

}
