<?php

use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\Core\Cache\RefinableCacheableDependencyInterface;
use Drupal\Core\Routing\StackedRouteMatchInterface;
use Drupal\Core\Url;
use Drupal\user\UserInterface;
use Drupal\search_api\Query\QueryInterface;

/**
 * Implements hook_mail().
 */
function nlc_prototype_mail($key, &$message, $params) {
  switch ($key) {
    case 'directory_access_token':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Secure access link: the Connect Directory');
      $message['body'] = $params['message'];
      break;
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function nlc_prototype_menu_local_tasks_alter(&$data, $route_name, RefinableCacheableDependencyInterface &$cacheability) {
  $account = \Drupal::currentUser();
  $roles = $account->getRoles();
  $these_roles = ['authenticated'];
  if (empty(array_diff($roles, $these_roles))) {
    $routes = [
      'entity.user.canonical',
      'entity.profile.type.user_profile_form',
    ];
    if (in_array($route_name, $routes)) {
      unset($data['tabs'][0]['entity.profile.user_profile_form:profile.type.role']);
    }
  }
}

/**
 * Define templates.
 */
function nlc_prototype_theme($existing, $type, $theme, $path) {
  return [
    'nlc_prototype_login_page' => [
      'variables' => [
        'check_url' => NULL,
      ]
    ],
    'nlc_connect_access_email_body' => [
      'variables' => [
        'pre' => NULL,
        'link' => NULL,
        'post' => NULL,
      ]
    ],
    'nlc_alert_title' => [
      'variables' => [
        'type' => 'h3',
        'title' => NULL,
      ]
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 *
 * Insert JavaScript to the appropriate scope/region of the page.
 */
function nlc_prototype_page_attachments(array &$page) {
  if (!empty($page['#attached']['library']) && in_array('google_analytics/google_analytics', $page['#attached']['library'])) {
    $page['#attached']['library'][] = 'nlc_prototype/google_analytics';
  }
}

/**
 * Implements hook_search_api_query_alter().
 * https://www.drupal.org/project/facets/issues/3018847
 */
function nlc_prototype_search_api_query_alter(QueryInterface &$query) {
  $facet_source_id = 'search_api:' . str_replace(':', '__', $query->getSearchId());
  $storage = \Drupal::entityTypeManager()->getStorage('facets_summary');
  // Get all the facet summaries for the facet source.
  $facet_summaries = $storage->loadByProperties(['facet_source_id' => $facet_source_id]);
  /** @var \Drupal\facets_summary\FacetsSummaryInterface $facet_summary */
  foreach ($facet_summaries as $facet_summary) {
    $processors = $facet_summary->getProcessors();
    // If the count processor is enabled, results count must not be skipped.
    if (in_array('show_count', array_keys($processors))) {
      $query->setOption('skip result count', FALSE);
      break;
    }
  }
}

/**
 * @param array $arguments
 * @param \Drupal\Core\Session\AccountProxyInterface $account
 */
function nlc_prototype_google_analytics_event_arguments_alter(&$arguments, &$account) {
  if (isset($arguments['user_id'])) {
    /** @var \Drupal\nlc_prototype\SalesforceMapping\NetworkIndividualMapping $account_sf_mappings */
    $account_sf_mappings = \Drupal::service('nlc_prototype.sf_mapping.network_individual');
    try {
      if ($account_sf_object = $account_sf_mappings->getAccountSfMappedObject()) {
        $arguments['user_id'] = google_analytics_user_id_hash($account_sf_object->sfid());
      }
    }
    catch (Exception $e) {
      // Do nothing here.
    }
  }
}

/**
 * Implements hook_js_settings_alter().
 */
function nlc_prototype_js_settings_alter(array &$settings, AttachedAssetsInterface $assets) {
  $current_user = \Drupal::currentUser();
  $route_match = \Drupal::routeMatch();
  if ($route_match instanceof StackedRouteMatchInterface) {
    $route_match = $route_match->getMasterRouteMatch();
  }
  if ($route_match->getRouteName()) {
    $url = Url::fromRouteMatch($route_match);
    $routeParams = $url->getRouteParameters();
    $settings['path']['currentPathIsSelfProfile'] = FALSE;
    if ($url->getRouteName() == 'entity.user.canonical' && $routeParams['user'] == $current_user->id()) {
      $settings['path']['currentPathIsSelfProfile'] = TRUE;
    }
  }
}
