#!/bin/bash

# see https://github.com/channable/vaultenv

# A wrapper around vaultenv to handle reading the token, setting env vars 
# to use and passing off to the real vaultenv progranm

# The token set by the vault init container 
export VAULT_TOKEN=$(cat /home/vault/.vault-token)

# vault address now set in pod along with CA file 
# export VAULT_ADDR=https://vault.vault.svc.cluster.local:8200

# What to read from vault 
export VAULTENV_SECRETS_FILE=/var/www/.vaultenv.secrets

# info or error 
export VAULTENV_LOG_LEVEL=error

exec /usr/bin/vaultenv -- $*


