#!/bin/bash

# see https://github.com/channable/vaultenv

# A wrapper around vaultenv to handle reading the token, setting env vars 
# to use and passing off to the real vaultenv progranm

# The token set by the vault init container 
export VAULT_TOKEN=$(cat /home/vault/.vault-token)

#  TEMPORARY ! will move to TLS
export VAULT_ADDR=http://vault-0.vault.vault.svc.cluster.local:8200

# What to read from vault 
export VAULTENV_SECRETS_FILE=/var/www/.vaultenv.secrets

# info or error 
export VAULTENV_LOG_LEVEL=info

exec /usr/bin/vaultenv -- $*


