account: UA-69921843-12
premium: false
domain_mode: 1
cross_domains: ''
visibility:
  request_path_mode: 0
  request_path_pages: "/admin\r\n/admin/*\r\n/batch\r\n/node/add*\r\n/node/*/*\r\n/user/*/*"
  user_role_mode: 1
  user_role_roles:
    nlc_staff: nlc_staff
    admin: admin
  user_account_mode: 0
track:
  outbound: true
  mailto: true
  files: true
  files_extensions: '7z|aac|arc|arj|asf|asx|avi|bin|csv|doc(x|m)?|dot(x|m)?|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt(x|m)?|pot(x|m)?|pps(x|m)?|ppam|sld(x|m)?|thmx|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls(x|m|b)?|xlt(x|m)|xlam|xml|z|zip'
  colorbox: true
  linkid: false
  urlfragments: false
  userid: false
  messages:
    status: status
    warning: warning
    error: error
  site_search: false
  adsense: false
  displayfeatures: true
privacy:
  anonymizeip: true
custom:
  dimension: {  }
  metric: {  }
codesnippet:
  create: {  }
  before: "(function(){\r\n    // Get a query string value, to track what is being search for\r\n    function getParameterByName(name) {\r\n        name = name.replace(/[\\[]/, \"\\\\[\").replace(/[\\]]/, \"\\\\]\");\r\n        var regex = new RegExp(\"[\\\\?&]\" + name + \"=([^&#]*)\"),\r\n        results = regex.exec(location.search);\r\n        return results === null ? \"\" : decodeURIComponent(results[1].replace(/\\+/g, \" \"));\r\n    };\r\n\r\n    window.onload = function(){\r\n        if(document.querySelector('h3.search-no-results') != null &&\r\n            document.querySelector('h3.search-no-results').innerText === \"Oops!\"){\r\n            var searchQuery = getParameterByName('search');\r\n            ga('send', 'event', 'Search','ZeroResults', searchQuery  ? searchQuery : 'Blank');\r\n        }\r\n    };\r\n\r\n    // Declare function to get selected text from document\r\n    function getSelectionText() {\r\n        var text = \"\";\r\n        var parentNodeHref = null;\r\n        if (window.getSelection && window.getSelection().anchorNode.parentNode.nodeName == \"A\") {\r\n            parentNodeHref = window.getSelection().anchorNode.parentNode.getAttribute('href');\r\n            text = window.getSelection().toString();\r\n        }\r\n        else if (document.selection && document.selection.type != \"Control\" && document.selection.createRange().parentElement().nodeName == \"A\") {\r\n             parentNodeHref = document.selection.createRange().parentElement().getAttribute('href');\r\n            text = document.selection.createRange().text;\r\n        }\r\n        var regexString = /\\bmailto:[a-zA-Z0-9@.]*|\\btel:[0-9]*/g\r\n        var regex = new RegExp(regexString);\r\n        results = regex.exec(parentNodeHref);\r\n        return results === null ? null : text;\r\n    }\r\n\r\n    // Declare function on copy event\r\n    document.addEventListener('copy', function(e){\r\n         var selectionText = getSelectionText();\r\n         if (selectionText !== null) {\r\n            ga('send', 'event', 'Connection', 'copy', selectionText);\r\n         }\r\n    });\r\n\r\n})();"
  after: ''
translation_set: false
cache: false
debug: false
_core:
  default_config_hash: Vx5EGxHruJuiMSwDv8Mg3PBf9RaPo8o2MCj8_QeTUhg
